../rtl/pkg/ddr4_ctrl_pkg.sv
../rtl/sync_fifo.sv
../rtl/async_fifo.sv
../rtl/ddr4_data_cache.sv
../rtl/ddr4_scheduler.sv
../rtl/phy/ddr4_fpga_clockgen.sv
../rtl/phy/ddr4_ck_out.sv
../rtl/ddr4_controller_top.sv
./model/ddr4_sdram_model.sv
./tb/ddr4_ctrl_tb.sv
