`timescale 1ns/1ps
module tb_ddr4_controller_m22;
  import ddr4_ctrl_pkg::*;
  localparam int TIMEOUT=12000;
  logic axi_clk=0,axi_rst_n=0,ddr_clk=0,ddr_rst_n=0;always #2.5 axi_clk=~axi_clk;always #1 ddr_clk=~ddr_clk;
  logic [5:0] awid,bid,arid,rid;logic [31:0] awaddr,wdata,araddr,rdata;logic [7:0] awlen,arlen;logic [2:0] awsize,arsize;logic [1:0] awburst,arburst,bresp,rresp;logic [3:0] wstrb;logic awvalid,awready,wlast,wvalid,wready,bvalid,bready,arvalid,arready,rlast,rvalid,rready;
  logic [31:0] paddr,pwdata,prdata;logic psel,penable,pwrite,pready,pslverr;
  logic ddr_ck_t,ddr_ck_c,ddr_reset_n,ddr_cke,ddr_cs_n,ddr_act_n,ddr_ras_n,ddr_cas_n,ddr_we_n;logic [1:0] ddr_bg,ddr_ba;logic [16:0] ddr_a;logic ddr_odt,ddr_par,ddr_alert_n;wire [15:0] ddr_dq;wire [1:0] ddr_dqs_t,ddr_dqs_c,ddr_dm_n;
  ddr4_controller_top #(.AXI_ID_W(6))dut(.axi_clk,.axi_rst_n,.clk(ddr_clk),.rst_n(ddr_rst_n),.s_axi_awid(awid),.s_axi_awaddr(awaddr),.s_axi_awlen(awlen),.s_axi_awsize(awsize),.s_axi_awburst(awburst),.s_axi_awvalid(awvalid),.s_axi_awready(awready),.s_axi_wdata(wdata),.s_axi_wstrb(wstrb),.s_axi_wlast(wlast),.s_axi_wvalid(wvalid),.s_axi_wready(wready),.s_axi_bid(bid),.s_axi_bresp(bresp),.s_axi_bvalid(bvalid),.s_axi_bready(bready),.s_axi_arid(arid),.s_axi_araddr(araddr),.s_axi_arlen(arlen),.s_axi_arsize(arsize),.s_axi_arburst(arburst),.s_axi_arvalid(arvalid),.s_axi_arready(arready),.s_axi_rid(rid),.s_axi_rdata(rdata),.s_axi_rresp(rresp),.s_axi_rlast(rlast),.s_axi_rvalid(rvalid),.s_axi_rready(rready),.paddr,.psel,.penable,.pwrite,.pwdata,.prdata,.pready,.pslverr,.ddr_ck_t,.ddr_ck_c,.ddr_reset_n,.ddr_cke,.ddr_cs_n,.ddr_act_n,.ddr_ras_n,.ddr_cas_n,.ddr_we_n,.ddr_bg,.ddr_ba,.ddr_a,.ddr_odt,.ddr_par,.ddr_alert_n,.ddr_dq,.ddr_dqs_t,.ddr_dqs_c,.ddr_dm_n);
  ddr4_sdram_model #(.DQ_W(16),.ADDR_W(17),.BA_W(2),.BG_W(2))dram(.reset_n(ddr_reset_n),.ck_t(ddr_ck_t),.ck_c(ddr_ck_c),.cke(ddr_cke),.cs_n(ddr_cs_n),.act_n(ddr_act_n),.ras_n(ddr_ras_n),.cas_n(ddr_cas_n),.we_n(ddr_we_n),.a(ddr_a),.ba(ddr_ba),.bg(ddr_bg),.odt(ddr_odt),.dq(ddr_dq),.dqs_t(ddr_dqs_t),.dqs_c(ddr_dqs_c),.dm_n(ddr_dm_n),.alert_n(ddr_alert_n));
  task automatic wait_init;integer n;begin n=0;while(!dut.init_done_sync2_axi&&n<TIMEOUT)begin @(posedge axi_clk);n++;end if(n==TIMEOUT)$fatal(1,"init timeout");end endtask
  task automatic write_id(input [5:0] id,input [31:0] a,input [31:0] d);integer n;begin @(posedge axi_clk);awid<=id;awaddr<=a;awvalid<=1;while(!awready)@(posedge axi_clk);@(posedge axi_clk);awvalid<=0;wdata<=d;wstrb<=4'hf;wlast<=1;wvalid<=1;while(!wready)@(posedge axi_clk);@(posedge axi_clk);wvalid<=0;wlast<=0;n=0;while(!bvalid&&n<TIMEOUT)begin @(posedge axi_clk);n++;end if(!bvalid||bid!==id)$fatal(1,"BID mismatch exp=%0d got=%0d",id,bid);@(posedge axi_clk);end endtask
  task automatic read_id(input [5:0] id,input [31:0] a,input [31:0] exp);integer n;begin @(posedge axi_clk);arid<=id;araddr<=a;arvalid<=1;while(!arready)@(posedge axi_clk);@(posedge axi_clk);arvalid<=0;n=0;while(!rvalid&&n<TIMEOUT)begin @(posedge axi_clk);n++;end if(!rvalid||rid!==id)$fatal(1,"RID mismatch exp=%0d got=%0d",id,rid);if(rdata!==exp)$fatal(1,"data mismatch");@(posedge axi_clk);end endtask
  initial begin awid=0;awaddr=0;awlen=0;awsize=2;awburst=1;awvalid=0;wdata=0;wstrb=0;wlast=0;wvalid=0;bready=1;arid=0;araddr=0;arlen=0;arsize=2;arburst=1;arvalid=0;rready=1;paddr=0;psel=0;penable=0;pwrite=0;pwdata=0;repeat(8)@(posedge axi_clk);axi_rst_n=1;repeat(8)@(posedge ddr_clk);ddr_rst_n=1;wait_init();write_id(6'h03,32'h2000,32'h11112222);write_id(6'h2a,32'h2004,32'h33334444);write_id(6'h03,32'h2008,32'h55556666);read_id(6'h2a,32'h2004,32'h33334444);read_id(6'h03,32'h2000,32'h11112222);read_id(6'h03,32'h2008,32'h55556666);$display("PASS M22 AXI 6-bit ID echo and per-ID ordering");$finish;end
  initial begin #300000;$fatal(1,"M22 timeout");end
endmodule
