// SPDX-License-Identifier: MIT
// DDR CK/CK# output wrapper.
//
// Define FPGA for the MPS3/Vivado build. In that environment the external
// DDR clock is generated by ddr4_fpga_clockgen using Xilinx clock-output
// primitives. Non-FPGA builds retain a portable behavioral fallback.

`timescale 1ns/1ps

module ddr4_ck_out (
  input  logic clk,
  output wire  ck_t,
  output wire  ck_c
);

`ifdef FPGA
  ddr4_fpga_clockgen u_fpga_clockgen (
    .clk_in    (clk),
    .ddr_clk_t (ck_t),
    .ddr_clk_c (ck_c)
  );
`else
  assign ck_t = clk;
  assign ck_c = ~clk;
`endif

endmodule : ddr4_ck_out
