+incdir+../../rtl/pkg
../../rtl/pkg/ddr4_ctrl_pkg.sv
../../rtl/sync_fifo.sv
../../rtl/async_fifo.sv
../../rtl/ddr4_data_cache.sv
../../rtl/core/ddr4_scheduler_v2.sv
../../rtl/core/ddr4_timing_ext.sv
../../rtl/core/ddr4_native_request_mux.sv
../../rtl/core/ddr4_m23_m28_engine.sv
../../rtl/core/ddr4_m29_axi_transaction_engine.sv
../../rtl/core/ddr4_m30_write_buffer.sv
../../rtl/core/ddr4_m31_victim_cache.sv
../../rtl/core/ddr4_m32_cache_subsystem.sv
../../rtl/core/ddr4_address_mapper.sv
../../rtl/phy/ddr4_x16_data_path.sv
../../rtl/core/ddr4_scheduler_open_page.sv
../../rtl/ddr4_scheduler.sv
../../rtl/phy/ddr4_fpga_clockgen.sv
../../rtl/phy/ddr4_ck_out.sv
../../rtl/phy/ddr4_dq_dqs_phy.sv
../../rtl/ddr4_controller_top.sv
